changelog:
  categories:
  - title: 🎁 Features
    labels:
    - '*'
    exclude:
      labels:
      - deps
      - fix
  - title: 🔧 Fixes
    labels:
    - fix
  - title: 📦 Dependencies
    labels:
    - deps