services:
  back:
    build: .
    env_file:
    - .env
    networks:
    - back

  front:
    build: ./internal/web
    environment:
    - AUTH_ORIGIN=http://localhost:3000
    ports:
    - 3000:3000
    networks:
    - back

networks:
  back: