/**
 * Quiz API
 * Quiz App backend
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface QuizQuestionAnswer
 */
export interface QuizQuestionAnswer {
  /**
   * The sha1 of the question answer
   * @type {string}
   * @memberof QuizQuestionAnswer
   */
  sha1?: string;
  /**
   * The question content
   * @type {string}
   * @memberof QuizQuestionAnswer
   */
  content?: string;
  /**
   * if the answer is checked or not
   * @type {boolean}
   * @memberof QuizQuestionAnswer
   */
  checked?: boolean;
  /**
   * if this is a valid answer
   * @type {boolean}
   * @memberof QuizQuestionAnswer
   */
  valid?: boolean | null;
}
