/**
 * Quiz API
 * Quiz App backend
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
import type { SessionResult } from "./session-result";

/**
 *
 * @export
 * @interface QuizSessionUserSessionsInner
 */
export interface QuizSessionUserSessionsInner {
  /**
     * The date of creation of the quiz
     * @type {string}
     * @memberof QuizSessionUserSessionsInner
     */
  sessionId?: string;
  /**
     * The id of the user
     * @type {string}
     * @memberof QuizSessionUserSessionsInner
     */
  userId?: string;
  /**
     * The firstname of the user
     * @type {string}
     * @memberof QuizSessionUserSessionsInner
     */
  userName?: string;
  /**
     * The avatar of the user
     * @type {string}
     * @memberof QuizSessionUserSessionsInner
     */
  picture?: string;
  /**
     * The class name of the user
     * @type {string}
     * @memberof QuizSessionUserSessionsInner
     */
  className?: string;
  /**
     * The remaining seconds before the end of the session
     * @type {number}
     * @memberof QuizSessionUserSessionsInner
     */
  remainingSec?: number | null;
  /**
     *
     * @type {SessionResult}
     * @memberof QuizSessionUserSessionsInner
     */
  result?: SessionResult | null;
}
