/**
 * Quiz API
 * Quiz App backend
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
import type { SessionResult } from "./session-result";

/**
 *
 * @export
 * @interface Session
 */
export interface Session {
  /**
     * The id of the session
     * @type {string}
     * @memberof Session
     */
  id?: string;
  /**
     * The sha1 of the quiz
     * @type {string}
     * @memberof Session
     */
  quizSha1?: string | null;
  /**
     * The name of the quiz
     * @type {string}
     * @memberof Session
     */
  quizName?: string | null;
  /**
     * If the session was realized on an active quiz or not
     * @type {boolean}
     * @memberof Session
     */
  quizActive?: boolean | null;
  /**
     * The id of the user
     * @type {string}
     * @memberof Session
     */
  userId?: string | null;
  /**
     * The firstname of the user
     * @type {string}
     * @memberof Session
     */
  userName?: string | null;
  /**
     * The remaining seconds before the end of the session
     * @type {number}
     * @memberof Session
     */
  remainingSec?: number | null;
  /**
     *
     * @type {SessionResult}
     * @memberof Session
     */
  result?: SessionResult | null;
}
