

/**
 * Quiz API
 * Quiz App backend 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Class } from './class';

/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * The id of the user
     * @type {string}
     * @memberof User
     */
    'id'?: string;
    /**
     * The username of the user
     * @type {string}
     * @memberof User
     */
    'login'?: string;
    /**
     * The full name of the user
     * @type {string}
     * @memberof User
     */
    'name'?: string;
    /**
     * The avatar of the user
     * @type {string}
     * @memberof User
     */
    'picture'?: string;
    /**
     * If the user is active or not
     * @type {boolean}
     * @memberof User
     */
    'active'?: boolean;
    /**
     * The role of the user
     * @type {string}
     * @memberof User
     */
    'role'?: UserRoleEnum;
    /**
     * 
     * @type {Class}
     * @memberof User
     */
    'class'?: Class;
}

export const UserRoleEnum = {
    NoRole: 'NO_ROLE',
    Student: 'STUDENT',
    Teacher: 'TEACHER',
    Admin: 'ADMIN'
} as const;

export type UserRoleEnum = typeof UserRoleEnum[keyof typeof UserRoleEnum];


