// Code generated by sqlc-addon. DO NOT EDIT.
// versions:
//   sqlc-addon v1.6.1

package db

import (
	"database/sql"
	"fmt"
	"log"
	"os"
	"os/signal"
	"syscall"

	_ "github.com/mattn/go-sqlite3"
)

func Connect(readOnly bool, databaseLocation string) *sql.DB {
	_, err := os.Stat(databaseLocation)
	if err != nil {
		err := os.MkdirAll(databaseLocation, 0700)
		if err != nil {
			log.Fatalf("Can't create database folder : %v (%v)\n", databaseLocation, err)
			os.Exit(-1)
		}
	}

	db, err := sql.Open("sqlite3", getDBUrl(readOnly, databaseLocation))
	if err != nil {
		log.Fatalf("Can't open database %v", err)
	}

	return db
}

func getDBUrl(readOnly bool, databaseLocation string) string {

	var options string
	if readOnly {
		options = "cache=shared&mode=ro"
	} else {
		options = "cache=shared&mode=rwc&_auto_vacuum=full&_journal_mode=WAL"
	}

	return fmt.Sprintf("file:%s/%s?%s", databaseLocation, "data.db", options)
}

func Init(databaseLocation string) *sql.DB {
	connection := Connect(false, databaseLocation)
	New(connection).Migrate()

	// Handles the CTRL+C properly
	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt, syscall.SIGTERM)

	go func() {
		<-c
		connection.Close()
		os.Exit(0)
	}()

	return connection
}
