// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqlc

import (
	"time"
)

type Quizz struct {
	Sha1      string    `db:"sha1"`
	Name      string    `db:"name"`
	Filename  string    `db:"filename"`
	Version   int64     `db:"version"`
	Active    int64     `db:"active"`
	CreatedAt time.Time `db:"created_at"`
}

type QuizzAnswer struct {
	Sha1    string `db:"sha1"`
	Valid   int64  `db:"valid"`
	Content string `db:"content"`
}

type QuizzQuestion struct {
	Sha1    string `db:"sha1"`
	Content string `db:"content"`
}

type QuizzQuestionAnswer struct {
	QuestionSha1 string `db:"question_sha1"`
	AnswerSha1   string `db:"answer_sha1"`
}

type QuizzQuestionQuizz struct {
	QuizzSha1    string `db:"quizz_sha1"`
	QuestionSha1 string `db:"question_sha1"`
}
