/*
 * Copyright (c) 2023 Michaël COLL.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: quizz.sql

package sqlc

import (
	"context"
)

const getQuizz = `-- name: GetQuizz :one
SELECT id,
       name
FROM quizz
WHERE id = ?
`

func (q *Queries) GetQuizz(ctx context.Context, db DBTX, id string) (Quizz, error) {
	row := db.QueryRowContext(ctx, getQuizz, id)
	var i Quizz
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
