// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: quizz.sql

package sqlc

import (
	"context"
)

const getQuizz = `-- name: GetQuizz :one
SELECT filename
FROM quizz
WHERE filename = ?
`

func (q *Queries) GetQuizz(ctx context.Context, db DBTX, filename string) (string, error) {
	row := db.QueryRowContext(ctx, getQuizz, filename)
	err := row.Scan(&filename)
	return filename, err
}
