/*
 * Copyright (c) 2023 Michaël COLL.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: user.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const clearClassUsers = `-- name: ClearClassUsers :exec
UPDATE user
SET class_uuid = NULL
WHERE class_uuid = ?
`

func (q *Queries) ClearClassUsers(ctx context.Context, classUuid uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, clearClassUsers, classUuid)
	return err
}

const createOrReplaceUser = `-- name: CreateOrReplaceUser :exec
REPLACE INTO user (id, login, name, picture, role_id)
VALUES (?, ?, ?, ?, ?)
`

type CreateOrReplaceUserParams struct {
	ID      string `db:"id"`
	Login   string `db:"login"`
	Name    string `db:"name"`
	Picture string `db:"picture"`
	RoleID  int8   `db:"role_id"`
}

func (q *Queries) CreateOrReplaceUser(ctx context.Context, arg CreateOrReplaceUserParams) error {
	_, err := q.db.ExecContext(ctx, createOrReplaceUser,
		arg.ID,
		arg.Login,
		arg.Name,
		arg.Picture,
		arg.RoleID,
	)
	return err
}

const findActiveUserById = `-- name: FindActiveUserById :one
SELECT id, login, name, picture, active, role_id, class_uuid, class_name
FROM user_class_view
WHERE id = ?
  AND active = 1
`

func (q *Queries) FindActiveUserById(ctx context.Context, id string) (UserClassView, error) {
	row := q.db.QueryRowContext(ctx, findActiveUserById, id)
	var i UserClassView
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Name,
		&i.Picture,
		&i.Active,
		&i.RoleID,
		&i.ClassUuid,
		&i.ClassName,
	)
	return i, err
}

const findAllUser = `-- name: FindAllUser :many
SELECT id, login, name, picture, active, role_id, class_uuid, class_name
FROM user_class_view
`

func (q *Queries) FindAllUser(ctx context.Context) ([]UserClassView, error) {
	rows, err := q.db.QueryContext(ctx, findAllUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserClassView{}
	for rows.Next() {
		var i UserClassView
		if err := rows.Scan(
			&i.ID,
			&i.Login,
			&i.Name,
			&i.Picture,
			&i.Active,
			&i.RoleID,
			&i.ClassUuid,
			&i.ClassName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUserById = `-- name: FindUserById :one
SELECT id, login, name, picture, active, role_id, class_uuid, class_name
FROM user_class_view
WHERE id = ?
`

func (q *Queries) FindUserById(ctx context.Context, id string) (UserClassView, error) {
	row := q.db.QueryRowContext(ctx, findUserById, id)
	var i UserClassView
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Name,
		&i.Picture,
		&i.Active,
		&i.RoleID,
		&i.ClassUuid,
		&i.ClassName,
	)
	return i, err
}

const updateUserActive = `-- name: UpdateUserActive :exec
UPDATE user
SET active = ?
WHERE id = ?
`

type UpdateUserActiveParams struct {
	Active bool   `db:"active"`
	ID     string `db:"id"`
}

func (q *Queries) UpdateUserActive(ctx context.Context, arg UpdateUserActiveParams) error {
	_, err := q.db.ExecContext(ctx, updateUserActive, arg.Active, arg.ID)
	return err
}

const updateUserClass = `-- name: UpdateUserClass :exec
UPDATE user
SET class_uuid = ?
WHERE id = ?
`

type UpdateUserClassParams struct {
	ClassUuid uuid.UUID `db:"class_uuid"`
	ID        string    `db:"id"`
}

func (q *Queries) UpdateUserClass(ctx context.Context, arg UpdateUserClassParams) error {
	_, err := q.db.ExecContext(ctx, updateUserClass, arg.ClassUuid, arg.ID)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE user
SET role_id = ?
WHERE id = ?
`

type UpdateUserRoleParams struct {
	RoleID int8   `db:"role_id"`
	ID     string `db:"id"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateUserRole, arg.RoleID, arg.ID)
	return err
}
