/*
 * Copyright (c) 2023 Michaël COLL.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Quiz API
 * Quiz App backend
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { QuizSessionUserSessionsInner } from "./quiz-session-user-sessions-inner";
// May contain unused imports in some cases
// @ts-ignore
import { SessionResult } from "./session-result";

/**
 *
 * @export
 * @interface QuizSession
 */
export interface QuizSession {
  /**
   * The sha1 of the whole quiz
   * @type {string}
   * @memberof QuizSession
   */
  quizSha1?: string;
  /**
   * The name of the quiz
   * @type {string}
   * @memberof QuizSession
   */
  name?: string;
  /**
   * The duration of the quiz in seconds
   * @type {number}
   * @memberof QuizSession
   */
  duration?: number;
  /**
   * The filename of the quiz
   * @type {string}
   * @memberof QuizSession
   */
  filename?: string | null;
  /**
   * The version of the quiz
   * @type {number}
   * @memberof QuizSession
   */
  version?: number | null;
  /**
   * The date of creation of the quiz
   * @type {string}
   * @memberof QuizSession
   */
  createdAt?: string | null;
  /**
   * The date of creation of the quiz
   * @type {string}
   * @memberof QuizSession
   */
  sessionId?: string | null;
  /**
   * The id of the user
   * @type {string}
   * @memberof QuizSession
   */
  userId?: string | null;
  /**
   * The firstname of the user
   * @type {string}
   * @memberof QuizSession
   */
  userName?: string | null;
  /**
   * The remaining seconds before the end of the session
   * @type {number}
   * @memberof QuizSession
   */
  remainingSec?: number | null;
  /**
   *
   * @type {SessionResult}
   * @memberof QuizSession
   */
  result?: SessionResult | null;
  /**
   * The list of all user session on the quiz
   * @type {Array<QuizSessionUserSessionsInner>}
   * @memberof QuizSession
   */
  userSessions?: Array<QuizSessionUserSessionsInner> | null;
}
