/**
 * Quiz API
 * Quiz App backend
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Quiz
 */
export interface Quiz {
  /**
   * The sha1 of the whole quiz
   * @type {string}
   * @memberof Quiz
   */
  sha1?: string;
  /**
   * The filename of the quiz
   * @type {string}
   * @memberof Quiz
   */
  filename?: string;
  /**
   * The name of the quiz
   * @type {string}
   * @memberof Quiz
   */
  name?: string;
  /**
   * The version of the quiz
   * @type {number}
   * @memberof Quiz
   */
  version?: number;
  /**
   * The date of creation of the quiz
   * @type {string}
   * @memberof Quiz
   */
  createdAt?: string;
  /**
   * The duration of the quiz in seconds
   * @type {number}
   * @memberof Quiz
   */
  duration?: number;
}
