/**
 * Quiz API
 * Quiz App backend
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SessionAnswerRequestBody
 */
export interface SessionAnswerRequestBody {
  /**
   * The sha1 of the question
   * @type {string}
   * @memberof SessionAnswerRequestBody
   */
  questionSha1?: string;
  /**
   * The sha1 of the answer
   * @type {string}
   * @memberof SessionAnswerRequestBody
   */
  answerSha1?: string;
  /**
   * If the answer is checked or not
   * @type {boolean}
   * @memberof SessionAnswerRequestBody
   */
  checked?: boolean;
}
