name: trivy
on:
  push:
    paths-ignore:
      - README.md
    tags-ignore:
      - '*'
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Trivy vulnerability scanner for backend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/michaelcoll/quiz-app-back:latest'
          format: 'sarif'
          output: 'trivy-results-back.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Run Trivy vulnerability scanner for frontend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/michaelcoll/quiz-app-front:latest'
          format: 'sarif'
          output: 'trivy-results-front.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab for backend
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results-back.sarif'

      - name: Upload Trivy scan results to GitHub Security tab for frontend
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results-front.sarif'
